"""added

Revision ID: 28ce8b0cc5b7
Revises: 5434af1433e7
Create Date: 2025-11-23 01:53:41.506582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ce8b0cc5b7'
down_revision: Union[str, Sequence[str], None] = '5434af1433e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pincodes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pincodes', type_='foreignkey')
    # ### end Alembic commands ###
