"""added

Revision ID: 28ce8b0cc5b7
Revises: 5434af1433e7
Create Date: 2025-11-23 01:53:41.506582

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '28ce8b0cc5b7'
down_revision: str | Sequence[str] | None = '5434af1433e7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pincodes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pincodes', type_='foreignkey')
    # ### end Alembic commands ###
