"""added

Revision ID: ad871ae78ebd
Revises: 28ce8b0cc5b7
Create Date: 2025-11-23 02:03:59.293946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad871ae78ebd'
down_revision: Union[str, Sequence[str], None] = '28ce8b0cc5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pincodes', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               postgresql_using="id::uuid",
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pincodes', 'id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               postgresql_using="id::text",
               existing_nullable=False)
    # ### end Alembic commands ###
